// Code generated by go-swagger; DO NOT EDIT.

package matchs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/capella/topcrush/models"
)

// DeleteMatchsDeleteCreatedCode is the HTTP code returned for type DeleteMatchsDeleteCreated
const DeleteMatchsDeleteCreatedCode int = 201

/*DeleteMatchsDeleteCreated delete matchs delete created

swagger:response deleteMatchsDeleteCreated
*/
type DeleteMatchsDeleteCreated struct {
}

// NewDeleteMatchsDeleteCreated creates DeleteMatchsDeleteCreated with default headers values
func NewDeleteMatchsDeleteCreated() *DeleteMatchsDeleteCreated {

	return &DeleteMatchsDeleteCreated{}
}

// WriteResponse to the client
func (o *DeleteMatchsDeleteCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

/*DeleteMatchsDeleteDefault generic error response

swagger:response deleteMatchsDeleteDefault
*/
type DeleteMatchsDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteMatchsDeleteDefault creates DeleteMatchsDeleteDefault with default headers values
func NewDeleteMatchsDeleteDefault(code int) *DeleteMatchsDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteMatchsDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete matchs delete default response
func (o *DeleteMatchsDeleteDefault) WithStatusCode(code int) *DeleteMatchsDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete matchs delete default response
func (o *DeleteMatchsDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete matchs delete default response
func (o *DeleteMatchsDeleteDefault) WithPayload(payload *models.Error) *DeleteMatchsDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete matchs delete default response
func (o *DeleteMatchsDeleteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMatchsDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
