// Code generated by go-swagger; DO NOT EDIT.

package matchs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/capella/topcrush/models"
)

// GetMatchsAllCreatedCode is the HTTP code returned for type GetMatchsAllCreated
const GetMatchsAllCreatedCode int = 201

/*GetMatchsAllCreated a list of users and chats

swagger:response getMatchsAllCreated
*/
type GetMatchsAllCreated struct {

	/*
	  In: Body
	*/
	Payload []*GetMatchsAllCreatedBodyItems0 `json:"body,omitempty"`
}

// NewGetMatchsAllCreated creates GetMatchsAllCreated with default headers values
func NewGetMatchsAllCreated() *GetMatchsAllCreated {

	return &GetMatchsAllCreated{}
}

// WithPayload adds the payload to the get matchs all created response
func (o *GetMatchsAllCreated) WithPayload(payload []*GetMatchsAllCreatedBodyItems0) *GetMatchsAllCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get matchs all created response
func (o *GetMatchsAllCreated) SetPayload(payload []*GetMatchsAllCreatedBodyItems0) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMatchsAllCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*GetMatchsAllCreatedBodyItems0, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetMatchsAllDefault generic error response

swagger:response getMatchsAllDefault
*/
type GetMatchsAllDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMatchsAllDefault creates GetMatchsAllDefault with default headers values
func NewGetMatchsAllDefault(code int) *GetMatchsAllDefault {
	if code <= 0 {
		code = 500
	}

	return &GetMatchsAllDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get matchs all default response
func (o *GetMatchsAllDefault) WithStatusCode(code int) *GetMatchsAllDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get matchs all default response
func (o *GetMatchsAllDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get matchs all default response
func (o *GetMatchsAllDefault) WithPayload(payload *models.Error) *GetMatchsAllDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get matchs all default response
func (o *GetMatchsAllDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMatchsAllDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
