// Code generated by go-swagger; DO NOT EDIT.

package slide

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/capella/topcrush/models"
)

// GetSlideUsersHandlerFunc turns a function with the right signature into a get slide users handler
type GetSlideUsersHandlerFunc func(GetSlideUsersParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSlideUsersHandlerFunc) Handle(params GetSlideUsersParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetSlideUsersHandler interface for that can handle valid get slide users params
type GetSlideUsersHandler interface {
	Handle(GetSlideUsersParams, *models.Principal) middleware.Responder
}

// NewGetSlideUsers creates a new http.Handler for the get slide users operation
func NewGetSlideUsers(ctx *middleware.Context, handler GetSlideUsersHandler) *GetSlideUsers {
	return &GetSlideUsers{Context: ctx, Handler: handler}
}

/*GetSlideUsers swagger:route GET /slide/users slide getSlideUsers

return a list of near users

*/
type GetSlideUsers struct {
	Context *middleware.Context
	Handler GetSlideUsersHandler
}

func (o *GetSlideUsers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSlideUsersParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
