// Code generated by go-swagger; DO NOT EDIT.

package slide

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/capella/topcrush/models"
)

// PutSlideSuperlikeHandlerFunc turns a function with the right signature into a put slide superlike handler
type PutSlideSuperlikeHandlerFunc func(PutSlideSuperlikeParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PutSlideSuperlikeHandlerFunc) Handle(params PutSlideSuperlikeParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PutSlideSuperlikeHandler interface for that can handle valid put slide superlike params
type PutSlideSuperlikeHandler interface {
	Handle(PutSlideSuperlikeParams, *models.Principal) middleware.Responder
}

// NewPutSlideSuperlike creates a new http.Handler for the put slide superlike operation
func NewPutSlideSuperlike(ctx *middleware.Context, handler PutSlideSuperlikeHandler) *PutSlideSuperlike {
	return &PutSlideSuperlike{Context: ctx, Handler: handler}
}

/*PutSlideSuperlike swagger:route PUT /slide/superlike slide putSlideSuperlike

make a superlike

*/
type PutSlideSuperlike struct {
	Context *middleware.Context
	Handler PutSlideSuperlikeHandler
}

func (o *PutSlideSuperlike) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutSlideSuperlikeParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
