// Code generated by go-swagger; DO NOT EDIT.

package slide

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutSlideBoastHandlerFunc turns a function with the right signature into a put slide boast handler
type PutSlideBoastHandlerFunc func(PutSlideBoastParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutSlideBoastHandlerFunc) Handle(params PutSlideBoastParams) middleware.Responder {
	return fn(params)
}

// PutSlideBoastHandler interface for that can handle valid put slide boast params
type PutSlideBoastHandler interface {
	Handle(PutSlideBoastParams) middleware.Responder
}

// NewPutSlideBoast creates a new http.Handler for the put slide boast operation
func NewPutSlideBoast(ctx *middleware.Context, handler PutSlideBoastHandler) *PutSlideBoast {
	return &PutSlideBoast{Context: ctx, Handler: handler}
}

/*PutSlideBoast swagger:route PUT /slide/boast slide putSlideBoast

make a boast

*/
type PutSlideBoast struct {
	Context *middleware.Context
	Handler PutSlideBoastHandler
}

func (o *PutSlideBoast) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutSlideBoastParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
