// Code generated by go-swagger; DO NOT EDIT.

package matches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetMatchesHandlerFunc turns a function with the right signature into a get matches handler
type GetMatchesHandlerFunc func(GetMatchesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMatchesHandlerFunc) Handle(params GetMatchesParams) middleware.Responder {
	return fn(params)
}

// GetMatchesHandler interface for that can handle valid get matches params
type GetMatchesHandler interface {
	Handle(GetMatchesParams) middleware.Responder
}

// NewGetMatches creates a new http.Handler for the get matches operation
func NewGetMatches(ctx *middleware.Context, handler GetMatchesHandler) *GetMatches {
	return &GetMatches{Context: ctx, Handler: handler}
}

/*GetMatches swagger:route GET /matches matches getMatches

GetMatches get matches API

*/
type GetMatches struct {
	Context *middleware.Context
	Handler GetMatchesHandler
}

func (o *GetMatches) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetMatchesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
