// Code generated by go-swagger; DO NOT EDIT.

package matches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/capella/topcrush/models"
)

// GetMatchesCreatedCode is the HTTP code returned for type GetMatchesCreated
const GetMatchesCreatedCode int = 201

/*GetMatchesCreated Get a list of matches 15 mathces

swagger:response getMatchesCreated
*/
type GetMatchesCreated struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewGetMatchesCreated creates GetMatchesCreated with default headers values
func NewGetMatchesCreated() *GetMatchesCreated {

	return &GetMatchesCreated{}
}

// WithPayload adds the payload to the get matches created response
func (o *GetMatchesCreated) WithPayload(payload *models.User) *GetMatchesCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get matches created response
func (o *GetMatchesCreated) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMatchesCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetMatchesPaymentRequiredCode is the HTTP code returned for type GetMatchesPaymentRequired
const GetMatchesPaymentRequiredCode int = 402

/*GetMatchesPaymentRequired subscription requerid

swagger:response getMatchesPaymentRequired
*/
type GetMatchesPaymentRequired struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMatchesPaymentRequired creates GetMatchesPaymentRequired with default headers values
func NewGetMatchesPaymentRequired() *GetMatchesPaymentRequired {

	return &GetMatchesPaymentRequired{}
}

// WithPayload adds the payload to the get matches payment required response
func (o *GetMatchesPaymentRequired) WithPayload(payload *models.Error) *GetMatchesPaymentRequired {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get matches payment required response
func (o *GetMatchesPaymentRequired) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMatchesPaymentRequired) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(402)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetMatchesDefault generic error response

swagger:response getMatchesDefault
*/
type GetMatchesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMatchesDefault creates GetMatchesDefault with default headers values
func NewGetMatchesDefault(code int) *GetMatchesDefault {
	if code <= 0 {
		code = 500
	}

	return &GetMatchesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get matches default response
func (o *GetMatchesDefault) WithStatusCode(code int) *GetMatchesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get matches default response
func (o *GetMatchesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get matches default response
func (o *GetMatchesDefault) WithPayload(payload *models.Error) *GetMatchesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get matches default response
func (o *GetMatchesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMatchesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
