// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetUserIDUploadHandlerFunc turns a function with the right signature into a get user ID upload handler
type GetUserIDUploadHandlerFunc func(GetUserIDUploadParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserIDUploadHandlerFunc) Handle(params GetUserIDUploadParams) middleware.Responder {
	return fn(params)
}

// GetUserIDUploadHandler interface for that can handle valid get user ID upload params
type GetUserIDUploadHandler interface {
	Handle(GetUserIDUploadParams) middleware.Responder
}

// NewGetUserIDUpload creates a new http.Handler for the get user ID upload operation
func NewGetUserIDUpload(ctx *middleware.Context, handler GetUserIDUploadHandler) *GetUserIDUpload {
	return &GetUserIDUpload{Context: ctx, Handler: handler}
}

/*GetUserIDUpload swagger:route GET /user/{id}/upload user getUserIdUpload

GetUserIDUpload get user ID upload API

*/
type GetUserIDUpload struct {
	Context *middleware.Context
	Handler GetUserIDUploadHandler
}

func (o *GetUserIDUpload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUserIDUploadParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
