// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostUserIDHandlerFunc turns a function with the right signature into a post user ID handler
type PostUserIDHandlerFunc func(PostUserIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUserIDHandlerFunc) Handle(params PostUserIDParams) middleware.Responder {
	return fn(params)
}

// PostUserIDHandler interface for that can handle valid post user ID params
type PostUserIDHandler interface {
	Handle(PostUserIDParams) middleware.Responder
}

// NewPostUserID creates a new http.Handler for the post user ID operation
func NewPostUserID(ctx *middleware.Context, handler PostUserIDHandler) *PostUserID {
	return &PostUserID{Context: ctx, Handler: handler}
}

/*PostUserID swagger:route POST /user/{id} user postUserId

PostUserID post user ID API

*/
type PostUserID struct {
	Context *middleware.Context
	Handler PostUserIDHandler
}

func (o *PostUserID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostUserIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
