// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostUserIDLocationHandlerFunc turns a function with the right signature into a post user ID location handler
type PostUserIDLocationHandlerFunc func(PostUserIDLocationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUserIDLocationHandlerFunc) Handle(params PostUserIDLocationParams) middleware.Responder {
	return fn(params)
}

// PostUserIDLocationHandler interface for that can handle valid post user ID location params
type PostUserIDLocationHandler interface {
	Handle(PostUserIDLocationParams) middleware.Responder
}

// NewPostUserIDLocation creates a new http.Handler for the post user ID location operation
func NewPostUserIDLocation(ctx *middleware.Context, handler PostUserIDLocationHandler) *PostUserIDLocation {
	return &PostUserIDLocation{Context: ctx, Handler: handler}
}

/*PostUserIDLocation swagger:route POST /user/{id}/location user postUserIdLocation

PostUserIDLocation post user ID location API

*/
type PostUserIDLocation struct {
	Context *middleware.Context
	Handler PostUserIDLocationHandler
}

func (o *PostUserIDLocation) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostUserIDLocationParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
