// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/capella/topcrush/models"
)

// PostUserIDCreatedCode is the HTTP code returned for type PostUserIDCreated
const PostUserIDCreatedCode int = 201

/*PostUserIDCreated Created

swagger:response postUserIdCreated
*/
type PostUserIDCreated struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewPostUserIDCreated creates PostUserIDCreated with default headers values
func NewPostUserIDCreated() *PostUserIDCreated {

	return &PostUserIDCreated{}
}

// WithPayload adds the payload to the post user Id created response
func (o *PostUserIDCreated) WithPayload(payload *models.User) *PostUserIDCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post user Id created response
func (o *PostUserIDCreated) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUserIDCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostUserIDDefault generic error response

swagger:response postUserIdDefault
*/
type PostUserIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostUserIDDefault creates PostUserIDDefault with default headers values
func NewPostUserIDDefault(code int) *PostUserIDDefault {
	if code <= 0 {
		code = 500
	}

	return &PostUserIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post user ID default response
func (o *PostUserIDDefault) WithStatusCode(code int) *PostUserIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post user ID default response
func (o *PostUserIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post user ID default response
func (o *PostUserIDDefault) WithPayload(payload *models.Error) *PostUserIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post user ID default response
func (o *PostUserIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUserIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
