// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/capella/topcrush/models"
)

// PutUserIDLocationHandlerFunc turns a function with the right signature into a put user ID location handler
type PutUserIDLocationHandlerFunc func(PutUserIDLocationParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PutUserIDLocationHandlerFunc) Handle(params PutUserIDLocationParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PutUserIDLocationHandler interface for that can handle valid put user ID location params
type PutUserIDLocationHandler interface {
	Handle(PutUserIDLocationParams, *models.Principal) middleware.Responder
}

// NewPutUserIDLocation creates a new http.Handler for the put user ID location operation
func NewPutUserIDLocation(ctx *middleware.Context, handler PutUserIDLocationHandler) *PutUserIDLocation {
	return &PutUserIDLocation{Context: ctx, Handler: handler}
}

/*PutUserIDLocation swagger:route PUT /user/{id}/location user putUserIdLocation

update user position

*/
type PutUserIDLocation struct {
	Context *middleware.Context
	Handler PutUserIDLocationHandler
}

func (o *PutUserIDLocation) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutUserIDLocationParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
