// Code generated by go-swagger; DO NOT EDIT.

package chat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetChatMessagesIDMessageIndexHandlerFunc turns a function with the right signature into a get chat messages ID message index handler
type GetChatMessagesIDMessageIndexHandlerFunc func(GetChatMessagesIDMessageIndexParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetChatMessagesIDMessageIndexHandlerFunc) Handle(params GetChatMessagesIDMessageIndexParams) middleware.Responder {
	return fn(params)
}

// GetChatMessagesIDMessageIndexHandler interface for that can handle valid get chat messages ID message index params
type GetChatMessagesIDMessageIndexHandler interface {
	Handle(GetChatMessagesIDMessageIndexParams) middleware.Responder
}

// NewGetChatMessagesIDMessageIndex creates a new http.Handler for the get chat messages ID message index operation
func NewGetChatMessagesIDMessageIndex(ctx *middleware.Context, handler GetChatMessagesIDMessageIndexHandler) *GetChatMessagesIDMessageIndex {
	return &GetChatMessagesIDMessageIndex{Context: ctx, Handler: handler}
}

/*GetChatMessagesIDMessageIndex swagger:route GET /chat/messages/{id}/{messageIndex} chat getChatMessagesIdMessageIndex

return all message from messageIndex

*/
type GetChatMessagesIDMessageIndex struct {
	Context *middleware.Context
	Handler GetChatMessagesIDMessageIndexHandler
}

func (o *GetChatMessagesIDMessageIndex) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetChatMessagesIDMessageIndexParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
