// Code generated by go-swagger; DO NOT EDIT.

package chat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/capella/topcrush/models"
)

// PutChatMessagesIDHandlerFunc turns a function with the right signature into a put chat messages ID handler
type PutChatMessagesIDHandlerFunc func(PutChatMessagesIDParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PutChatMessagesIDHandlerFunc) Handle(params PutChatMessagesIDParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PutChatMessagesIDHandler interface for that can handle valid put chat messages ID params
type PutChatMessagesIDHandler interface {
	Handle(PutChatMessagesIDParams, *models.Principal) middleware.Responder
}

// NewPutChatMessagesID creates a new http.Handler for the put chat messages ID operation
func NewPutChatMessagesID(ctx *middleware.Context, handler PutChatMessagesIDHandler) *PutChatMessagesID {
	return &PutChatMessagesID{Context: ctx, Handler: handler}
}

/*PutChatMessagesID swagger:route PUT /chat/messages/{id} chat putChatMessagesId

send a message in a chat

*/
type PutChatMessagesID struct {
	Context *middleware.Context
	Handler PutChatMessagesIDHandler
}

func (o *PutChatMessagesID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutChatMessagesIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
