// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Images images
// swagger:model images
type Images struct {

	// id
	// Read Only: true
	// Format: ObjectId
	ID strfmt.ObjectId `json:"_id,omitempty"`

	// upload date
	// Format: date-time
	UploadDate strfmt.DateTime `json:"uploadDate,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this images
func (m *Images) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUploadDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Images) validateID(formats strfmt.Registry) error {

	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.FormatOf("_id", "body", "ObjectId", m.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Images) validateUploadDate(formats strfmt.Registry) error {

	if swag.IsZero(m.UploadDate) { // not required
		return nil
	}

	if err := validate.FormatOf("uploadDate", "body", "date-time", m.UploadDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Images) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Images) UnmarshalBinary(b []byte) error {
	var res Images
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
